name: Run Python script daily

on:
  schedule:
    - cron: '24 7 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          npm install -g npm@latest # Update npm to the latest version
          npm install -g yarn # Install yarn package manager
          yarn global add typescript # Install TypeScript globally
          pip install requests twilio python-dotenv

      - name: Run Python script
        run: python main.py
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          YOUR_PHONE_NUMBER: ${{ secrets.YOUR_PHONE_NUMBER }}
          WEATHER_API_URL: ${{ secrets.WEATHER_API_URL }}
